// Generated from skills/*/skill.zip (SKILL.md bodies). Edit the skill files, then regenerate; do not hand-edit.
export const SKILL_TEXT: Record<string, string> = {
  "coach-chief-of-staff": "Act as the orchestration layer for a junior-high or high-school football coach. Start from the coach's real constraint: opponent, game date, practice time, personnel, installation priorities, injuries/availability, and staff needs. Do not invent team facts.\n\n## Workflow\n1. Identify the coaching job to be done and required deadline.\n2. Pull together only the relevant known context.\n3. Delegate conceptually to the specialist workflow(s) listed below when available.\n4. Resolve conflicts across practice time, player availability, game-plan priorities, and communication.\n5. Return one coherent action plan with next actions and artifacts.\n\n## Specialist workflows\n- `practice-plan-builder`\n- `game-plan-builder`\n- `script-builder`\n- `opponent-scout`\n- `roster-depth-chart-manager`\n- `player-development`\n- `staff-briefing`\n- `game-day-command-center`\n- `postgame-review`\n- `parent-player-comms`\n\n## Operating rules\n- Optimize for sideline/practice usability, not football-theory verbosity.\n- Keep terminology consistent with the team's own language when supplied.\n- Separate varsity/JV/junior-high needs when relevant.\n- Never treat an AI suggestion as a medical clearance, eligibility ruling, or school-policy decision.\n- When data is missing, mark assumptions clearly.",
  "game-day-command-center": "Build a compact game-day packet from approved plans. Include timeline, staff responsibilities, depth/personnel alerts, opening priorities, situational menu, special-teams checklist, halftime capture prompts, and emergency contacts/process placeholders if supplied. Optimize for fast scanning. Never invent school emergency procedures.",
  "game-plan-builder": "Turn scouting evidence and team capabilities into a concise game plan. Separate evidence from inference. Structure around: opponent identity/tendencies, our advantages/constraints, core calls, complements/counters, situational plan, special teams, personnel alerts, and practice installation sequence. Prefer a small executable menu over an oversized call sheet.",
  "opponent-scout": "Analyze only the evidence provided. Organize findings by personnel, formation, field position, down-distance, motion/shift, run/pass concept, pressure/coverage, explosive plays, and special teams when data supports it. Show sample size. Distinguish strong tendency, weak signal, and unknown. Translate findings into testable coaching implications without overstating certainty.",
  "parent-player-comms": "Draft concise communication from supplied facts. Put the action/date/time first. Avoid sharing private player information, discipline details, or sensitive family information. When the topic involves policy, eligibility, discipline, transportation, or safety, preserve the school's official language when provided and flag anything requiring administrator confirmation.",
  "player-development": "Convert observations into 1-3 specific development priorities per player, observable behaviors, drills/reps, coaching cues, and review checkpoints. Keep feedback age-appropriate and constructive. Do not diagnose medical, psychological, or learning conditions. Focus on coach-observable football behaviors.",
  "postgame-review": "Separate outcome from process. Summarize what worked, what failed, evidence, likely causes, and what must change. Tag items as scheme, technique, assignment, communication, personnel, or preparation. Convert findings into no more than five next-week priorities and identify which practice periods should address them.",
  "practice-plan-builder": "Build a field-ready practice plan. Capture total minutes, day of week, opponent/game context, install priorities, special teams, position needs, available players, equipment/space constraints, and desired tempo. Allocate every minute. Include period name, duration, groups, objective, setup, coaching emphasis, and transition notes. Flag overloaded plans and recommend what to cut first. End with 3-5 success checks for the head coach.",
  "roster-depth-chart-manager": "Maintain one canonical player record. Preserve supplied school/eligibility decisions rather than making them. Detect duplicate assignments, thin position groups, players assigned to simultaneous special-teams roles, and missing backups. Produce concise depth charts and change summaries. Treat health details as restricted context and minimize unnecessary exposure.",
  "script-builder": "Create numbered, executable scripts. Ask or infer only when safe: play/call inventory, hash, field position, down-distance, personnel, formation/front, desired situations, and rep count. Balance repetition of priorities with realistic variation. Include a compact coach-notes column and an optional result/grade field for live use.",
  "staff-briefing": "Create a common team brief plus role-specific sections. Make ownership explicit: who owns what, by when, and what success looks like. Surface unresolved decisions and dependencies. Keep the output skimmable enough to use in a staff meeting."
};
